# Group AbuseReports
Abuse reports targeted posts (articles).

An AbuseReport resource has the following attributes:

- Id
- CreatedAt
- PostId
- UserId
- Description

The attributes *Id*, *CreatedAt*, and *UserId* are set by the TrunkTrunk API.


## AbuseReports [/abuse_reports]
Actions on the collection of all abuse reports.

### Create an AbuseReport [POST]

+ Request (application/json)

        {
          "PostId": 8,
          "Description": "Abuse report description"
        }

+ Response 201 (application/json)

        {
          "Id": 1,
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "PostId": 8,
          "UserId": 2,
          "Description": "Abuse report description"
        }
