# Group Accesses

Access defines whether a user has access to a post.
Access to a post is given to a user if:

- The post is freely available (eg. free or not on newsquid)
- The user has previously bought the post

An Access resource has the following attribute:

- **HasAccess**: (bool, required)


## -> /accesses/{userId}/{postId} [/accesses/{userId}/{postId}]

+ Parameters
    + id (required, number, `1`) ... Id of the group.

### Get [GET]

Returns whether the user has access to the post

+ Response 200 (application/json)

        {
          "HasAccess": true,
        }
