# Group Admin
Admin part of the API, defines special endpoints only avaiable to admins

Featured, a featured resource has the following attributes:
- **Featured**: (bool, required) Indicates if the entity is featured or not


## -> /admin/posts/{id}/featured [/admin/posts/{id}/featured]

### Put [PUT]
Put Featured for a post

Only admins can do this call

+ Request 200 (application/json)
    {
        Featured: true
    }

+ Response 201 (application/json)
    {
        Featured: true
    }

## -> /admin/users/{id}/featured [/admin/users/{id}/featured]

### Put [PUT]
Put Featured for a user

Only admins can do this call

+ Request 200 (application/json)
    {
        Featured: true
    }

+ Response 201 (application/json)
    {
        Featured: true
    }

