# Group ExternalPublishers
External publishers referenced by the users of the blogging platform. This can
be publishers such as New York times or The Wall Street Journal.

An ExternalPublisher resource has the following attributes:

- **Id**: (int, required) Unique identifier
- **UserId**: (int, required) The id of the user who registered the publisher
- **CreatedAt**: (datetime, required) The time of creation of the resource
- **UpdatedAt**: (datetime, required) The latest time of modification of the resource
- **Url**: (string, required) URL to the website of the external publisher
- **ImageUrl**: (string, optional) URL to the logo of the external publisher

The attributes *Id*, *CreatedAt*, and *UpdatedAt* are set by the TrunkTrunk API.


## -> /external/publishers [/external/publishers]

### Get [GET]
Get a list of all external publishers.

Any user can do this request. The caller does not need to be signed in.

+ Response 200 (application/json)
        
        [
            {
              "Id": 1, 
              "CreatedAt": "2014-04-14T02:15:15Z", 
              "UpdatedAt": "2014-04-14T02:15:15Z", 
              "Url": "http://www.example.org/", 
              "ImageUrl": "http://oi60.tinypic.com/2s7yhvt.jpg"
            },
            {
              "Id": 2, 
              "CreatedAt": "2014-04-14T02:15:15Z", 
              "UpdatedAt": "2014-04-14T02:15:15Z", 
              "Url": "http://www.nytimes.com", 
              "ImageUrl": "http://www.b.dk/sites/www.b.dk/favicon.ico"
            }
        ]

### Create [POST]
Create a new external publisher.

Any signed in user is allowed to do this request.

+ Request (application/json)

        {
          "UserId": 1
          "Url": "http://www.example.org/", 
          "ImageUrl": "http://oi60.tinypic.com/2s7yhvt.jpg"
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Url": "http://www.example.org/", 
          "ImageUrl": "http://oi60.tinypic.com/2s7yhvt.jpg"
        }


## -> /external/publishers/{id} [/external/publishers/{id}]

+ Parameters
    + id (required, number, `1`) ... Id of the ExternalPublisher.

### Get [GET]
Get the external publisher with the given id.

Any user can do this request. The caller does not need to be signed in.

+ Response 200 (application/json)

        {
          "Id": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Url": "http://www.example.org/", 
          "ImageUrl": "http://oi60.tinypic.com/2s7yhvt.jpg"
        }
