# Group GroupMemberships 
The connection between groups and users and vice versa.

A GroupMembership resource has the following attributes:

- Id
- CreatedAt
- UpdatedAt
- GroupId
- UserId 
- Status

The attributes *Id*, *CreatedAt*, *UpdatedAt*, and *Status* are set by the TrunkTrunk API.


## GroupMemberships [/groups/memberships]
Actions on the collection of all group memberships.

### Create a GroupMembership [POST]

+ Request (application/json)

        {
          "GroupId": 7,
          "UserId": 3
        }

+ Response 201 (application/json)

        {
          "Id": 4,
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "GroupId": 7,
          "UserId": 3,
          "Status": "Pending"
        }

### Update a GroupMembership [PATCH]

+ Request (application/json)

        {
          "Id": 4
        }

+ Response 201 (application/json)

        {
          "Id": 4,
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-23T06:06:15Z", 
          "GroupId": 7,
          "UserId": 3,
          "Status": "Active"
        }


## Single GroupMembership [/groups/memberships/{id}]
Actions on single GroupMembership resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the GroupMembership on which the action is done.

### Delete a GroupMembership [DELETE]
+ Response 204
