# Group GroupMemberships 
The connection between groups and users and vice versa.

A GroupMembership resource has the following attributes:

- **Id**: (int, required) Unique identifier
- **Token**: (string, required) A unique token granting permission to accept and reject group invites
- **CreatedAt**: (datetime, required) The time of creation of the resource
- **UpdatedAt**: (datetime, required) The latest time of modification of the resource
- **GroupId**: (int, required) Identifier of the group to which the membership applies
- **InviterId**: (int, required) Identifier of the user who made the invitation
- **InviteeId**: (int) Identifier of the user to which the membership applies
- **InviteeEmail**: (string) Email address to send invitation to
- **Status**: (string, required) The status of the membership. When a 
membership is first created, the status is "pending". When a membership is
accepted, the status changes to "active". Alternatively, an invitation can be rejected by setting the status to "rejected".

The attributes *Id*, *CreatedAt*, *UpdatedAt*, *Token*, *InviterId*, and *Status* are set by the TrunkTrunk API.


## -> /groups/memberships [/groups/memberships]

### Create [POST]
Create a new group membership. The creation results in the creation of a new
GroupMembership ship resource with the status "pending" as well as in an
invitation email to the user invited to join the group.
An invitation must contain *either* an **InviteeId** *or* an **InviteeEmail**, never both, as the presence of **InviteeEmail** will indicate that the user does not exist on trunktrunk, and should be invited by email.

Any member of a group can invite other users to join it.

+ Request (application/json)

        {
          "GroupId": 7,
          "InviteeId": 3
        }

+ Response 201 (application/json)

        {
          "Id": 4,
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "GroupId": 7,
          "Invitee": 3,
          "Status": "Pending"
        }

### Update [PATCH]
Accept or reject the group membership. This results in the status of the resource
changing from "pending" to "active" or "rejected". 
The idea is to give users the option to accept an invitation (by this request) or decline it.
To identify the membership, either **Id** or **Token** is sufficient.

Only the user to which to group membership applies can update it.

+ Request (application/json)

        {
          "Token": "c2246bef37c1373590b58c406634a6cd"
          "Status": "Active"
        }

+ Response 201 (application/json)

        {
          "Id": 4,
          "Token": "c2246bef37c1373590b58c406634a6cd"
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-23T06:06:15Z", 
          "GroupId": 7,
          "UserId": 3,
          "Status": "Active"
        }


## -> /groups/memberships/{id} [/groups/memberships/{id}]

+ Parameters
    + id (required, number, `1`) ... Id of the GroupMembership.

### Delete a GroupMembership [DELETE]
Delete the GroupMembership with the given id. This corresponds to leaving a group.

Only the invited or the inviting user can delete it.

+ Response 204
