# Group Posts
Posts (articles) at the core of the blogging platform.

A Post resource has the following attributes:

- Id
- Revision
- CreatedAt
- UpdatedAt
- Title
- Content
- Tags
- PublishedRevision

The attributes *Id*, *Revision*, *CreatedAt*, and *UpdatedAt* are set by the TrunkTrunk API.


## Posts [/posts]
Actions on the collection of all posts.

### Create a Post [POST]
If the *published* attribute is set to true, the post is published. Otherwise it is saved as a draft.

+ Request (application/json)

        {
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ]
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 0
        }

### Update a Post [PUT]
The revision id must be the latest revision id. Otherwise the request is rejected.

+ Request (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }



## Single post [/posts/{id}]
Actions on single Post resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Post on which the action is done.

### Retrieve a Post [GET]
+ Response 200 (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 1
        }

### Remove a Post [DELETE]
+ Response 204


## Single post as a draft [/posts/{id}/draft]
Actions on the newest draft of single Post resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Post on which the action is done.

### Retrieve a Post [GET]
+ Response 200 (application/json)

        {
          "Id": 1, 
          "Revision": 5, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }


## Posts by user [/posts/user/{id}]
Actions on the collection of posts owned by a single user.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the owner of the posts on which the action is done.

### Retrieve all posts by user [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 3
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }]


## Posts by group [/posts/group/{id}]
Actions on the collection of posts in a single group.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the group to which the posts on which the action is done belong.

### Retrieve all posts by group [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 3
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }]



## Featured posts [/posts/featured]
Actions on the collection of featured posts.

### Retrieve all featured post [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 3
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }]

## Search [/posts{?search}]
Retrieve all posts matching the given search parameter.

+ Parameters
    + search (required, string) ... Search string. The terms with which to search.

### Search for posts [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 3
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "PublishedRevision": 2
        }]
