# Group Posts
Posts (articles) at the core of the blogging platform.

A Post resource has the following attributes:

- id
- revision
- created_at
- updated_at
- title
- content
- tags
- published

The attributes *id*, *revision*, *created_at*, and *updated_at* are set by the TrunkTrunk API.


## Actions on the collection of posts [/posts]

### Create a Post [POST]
+ Request (application/json)

        {
          "title": "Post 1", 
          "content": "Content of Post 1", 
          "tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "published": "true"
        }

+ Response 201 (application/json)

        {
          "id": 1, 
          "revision": "1", 
          "created_at": "2014-04-14T02:15:15Z", 
          "updated_at": "2014-04-14T02:15:15Z", 
          "title": "Post 1", 
          "content": "Content of Post 1", 
          "tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "published": "true"
        }


## Actions on the collection of features posts [/posts/featured]

### Get all features posts [GET]
+ Response 200 (application/json)

        [{
          "id": 1, 
          "revision": "3", 
          "created_at": "2014-04-14T02:15:15Z", 
          "updated_at": "2014-04-14T02:15:15Z", 
          "title": "Post 1", 
          "content": "Content of Post 1", 
          "tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "published": "true"
        }, {
          "id": 2, 
          "revision": "2", 
          "created_at": "2014-04-14T02:15:15Z", 
          "updated_at": "2014-04-14T02:15:15Z", 
          "title": "Post 2", 
          "content": "Content of Post 2", 
          "tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "published": "true"
        }]

## Actions on single Post resources [/notes/{id}]
A single Note object with all its details

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Post to perform action with. Has example value.

### Retrieve a Note [GET]
+ Response 200 (application/json)

        {
          "id": 1, 
          "revision": "1", 
          "created_at": "2014-04-14T02:15:15Z", 
          "updated_at": "2014-04-14T02:15:15Z", 
          "title": "Post 1", 
          "content": "Content of Post 1", 
          "tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "published": "true"
        }

### Remove a Note [DELETE]
+ Response 204
