# Group Posts
Posts (articles) at the core of the blogging platform.

A Post resource has the following attributes:

- Id
- Revision
- CreatedAt
- UpdatedAt
- Title
- Content
- Tags
- Published

The attributes *id*, *revision*, *created_at*, and *updated_at* are set by the TrunkTrunk API.


## Posts [/posts]
Actions on the collection of all posts.

### Create a Post [POST]
If the *published* attribute is set to true, the post is published. Otherwise it is saved as a draft.

+ Request (application/json)

        {
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }

### Update a Post [PUT]
If the *published* attribute is set to true, the post is published. Otherwise
it is saved as a draft, and the previous published version remains published.
The revision id must be the latest revision id. Otherwise the request is rejected.

+ Request (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }



## Single post [/posts/{id}]
Actions on single Post resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the Post on which the action is done.

### Retrieve a Post [GET]
+ Response 200 (application/json)

        {
          "Id": 1, 
          "Revision": 1, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }

### Remove a Post [DELETE]
+ Response 204


## Posts by user [/posts/user/{id}]
Actions on the collection of posts owned by a single user.

### Retrieve all posts by user [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }]



## Featured posts [/posts/featured]
Actions on the collection of featured posts.

### Retrieve all featured post [GET]
+ Response 200 (application/json)

        [{
          "Id": 1, 
          "Revision": 3, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 1", 
          "Content": "Content of Post 1", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }, {
          "Id": 2, 
          "Revision": 2, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Title": "Post 2", 
          "Content": "Content of Post 2", 
          "Tags" [
            "Tag 1", "Tag 2", "Tag 3"
          ],
          "Published": "true"
        }]

