# Group UserSessions
Handles user sessions (sign in/out).

A Session resource has the following attributes:

- **UserId**: (int, required) Unique identifier of the user of which the session is concerned 
- **CreatedAt**: (datetime, required) The time of creation of the resource
- **UpdatedAt**: (datetime, required) The latest time of modification of the resource
- **ExpiresAt**: (datetime, required) The time of expiration of the session. After this time, the user will have to reauthenticate. 
- **Token**: (string, required) The token used for authenticating the user 

All attributes are set by the TrunkTrunk API.


## -> /users/sessions [/users/sessions]

### Create [POST]
Create a new user session. Expects a valid Newsquid token as request data. 

+ Request (application/json)
        
        {
            "Token": "NewsquidToken"
        }

+ Response 201 (application/json)

        {
          "UserId": 2,
          "CreatedAt": "2014-04-14T02:15:15Z",
          "UpdatedAt": "2014-04-18T02:15:15Z",
          "ExpiresAt": "2014-04-18T03:15:15Z",
          "Token": "QWxhZGRpbjpvcGVuIHNlc2FtZQ"
        }


### Delete [DELETE]
Destroys (expires) the session of the user currently logged in

+ Response 204
