# Group Users
Users of the blogging platform.

A User resource has the following attributes:

- Id
- NewsquidId
- CreatedAt
- UpdatedAt
- Name
- Email
- Title
- Description
- FacebookLink
- TwitterLink
- GooglePlusLink
- LinkedInLink
- WebsiteLink

The attributes *Id*, *NewsquidId*, *Token*, *CreatedAt*, and *UpdatedAt* are set by the TrunkTrunk API.


## Users [/users]
Actions on the collections of Users.

### Retrieve the current user[GET]
Get the User resource of the user currently logged in.

+ Response 200 (application/json)

        {
          "Id": 1, 
          "NewsquidId": 7, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Name": "User 1",
          "Email": "user1@example.org",
          "Title": "Freelance writer", 
          "Description": "Description of User 1",
          "FacebookLink": "",
          "TwitterLink": "",
          "GooglePlusLink": "",
          "LinkedInLink": "",
          "WebsiteLink": ""
        }


### Update a User [PUT]
Update the user information of the current user.

+ Request (application/json)

        {
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Name": "Updated User 1",
          "Email": "user1@example.org",
          "Title": "Freelance writer", 
          "Description": "New description of User 1",
          "FacebookLink": "",
          "TwitterLink": "",
          "GooglePlusLink": "",
          "LinkedInLink": "",
          "WebsiteLink": "http://www.trunktrunk.com/user1"
        }

+ Response 201 (application/json)

        {
          "Id": 1, 
          "NewsquidId": 7, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Name": "Updated User 1",
          "Email": "user1@example.org",
          "Title": "Freelance writer", 
          "Description": "New description of User 1",
          "FacebookLink": "",
          "TwitterLink": "",
          "GooglePlusLink": "",
          "LinkedInLink": "",
          "WebsiteLink": "http://www.trunktrunk.com/user1"
        }
 

## Single user [/users/{id}]
Actions on single User resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the User on which the action is done.

### Retrieve a User [GET]
+ Response 200 (application/json)

        {
          "Id": 1, 
          "NewsquidId": 7, 
          "CreatedAt": "2014-04-14T02:15:15Z", 
          "UpdatedAt": "2014-04-14T02:15:15Z", 
          "Name": "User 1",
          "Email": "user1@example.org",
          "Title": "Freelance writer", 
          "Description": "Description of User 1",
          "FacebookLink": "",
          "TwitterLink": "",
          "GooglePlusLink": "",
          "LinkedInLink": "",
          "WebsiteLink": ""
        }


## Users by group [/users/group/{id}]
Actions on the users members of a single Group resource.

+ Parameters
    + id (required, number, `1`) ... Numeric `id` of the group whose members (users) are target of the action to be done.

### Retrieve groups [GET]
+ Response 200 (application/json)

        [
            {
              "Id": 1, 
              "NewsquidId": 7, 
              "CreatedAt": "2014-04-14T02:15:15Z", 
              "UpdatedAt": "2014-04-14T02:15:15Z", 
              "Name": "User 1",
              "Email": "user1@example.org",
              "Title": "Freelance writer", 
              "Description": "Description of User 1",
              "FacebookLink": "",
              "TwitterLink": "",
              "GooglePlusLink": "",
              "LinkedInLink": "",
              "WebsiteLink": ""
            },
            {
              "Id": 3, 
              "NewsquidId": 23, 
              "CreatedAt": "2014-04-14T02:15:15Z", 
              "UpdatedAt": "2014-04-14T02:15:15Z", 
              "Name": "User 3",
              "Email": "user3@example.org",
              "Title": "Freelance publisher", 
              "Description": "Description of User 3",
              "FacebookLink": "http://facebook.com/user3",
              "TwitterLink": "http://twitter.com/user3",
              "GooglePlusLink": "",
              "LinkedInLink": "",
              "WebsiteLink": ""
            }
        ]
